### PR TITLE
Bugfixes attempt 2

### PR DESCRIPTION
**Pull request by thet**
Follow-Up from https://github.com/Patternslib/generator-patternslib/pull/1

### CODE REVIEW

**Comment by thet** [comment]
If this one goes OK, please also release a new generator-patternslib version on npm. I'd like to write a mail to the conf mailinglist to let people know, that the generator produces now code, which works as expected. We run into some issues at the training.

**Comment by jcbrand** [comment]
Thanks for the work on this @thet!

Sorry that it was still buggy during training. :(

**Comment by jcbrand** [comment]
I've set the JSON indentation back to 2 spaces, because that's how those files are generated by bower and npm respectively.

I just want to test this out once then I'll make a tag and release to NPM. I'm leaving soon, so it might only be later tonight.

**Comment by jcbrand** [comment]
For some reason the README.md file doesn't land in the generated pattern. I've run out of time for now, will check later again.

**Comment by thet** [comment]
@jcbrand no need to apologize ! :) it was not a problem.
thank you for creating the pattern generator!

**Comment by jcbrand** [comment]
@thet: Tagged and released to NPM: https://www.npmjs.com/package/generator-patternslib

**Comment by thet** [comment]
@jcbrand tnx!

**Pull request merged**
